### ISSUE TITLE
PHP 7.4 Deprecation: Swap arguments for join

### ISSUE THREAD

**Issue by JanBartels** [simonschaufi/macina_banners#4]
With PHP 7.4 the used calling signature for join() (implode()) is deprecated. The arguments of join have to be swapped (lines 359 and 474 of Pi1.php):

`
$banner = join($img, $wrappedSubpartArray['###bannerlink###']);
`

See https://www.php.net/manual/de/function.implode.php

**Comment by simonschaufi** [comment]
Since I don't have any website where this extension is in use, should I hand this extension over to you as you use it?

**Comment by JanBartels** [comment]
I'm just migrating a TYPO3 9 instance to a new server running a newer PHP version, when I discovered this issue. As the ext still uses quite outdated techniques (pi-based plugin and marker templates instead of extbase/fluid) we might drop the ext when updating to TYPO3 10 in the near future. So far, I haven't tried if the ext is running under TYPO3 10. Let us defer the decision of taking over the ext until we have decided whether we will drop or continue to use the ext.

I opened this issue mainly to inform other users what to do if they encounter the same problem.

**Comment by simonschaufi** [comment]
Well, pi-based plugins still work great and very performant, much faster than extbase actually but if you want to continue contributing to the ext, you can refactor everything if you want. I don't have the passion to do it when there are no users of the extension...

By the way, it won't work with TYPO3 10 because it still uses those really old db methods like `exec_SELECTquery()` so this definitely needs to be rewritten to the new QueryBuilder but maybe rector could be able to migrate lots of outdated code without much effort :smile: 

In the meantime I can fix this issue of course ;)

**Comment by simonschaufi** [comment]
Released a new version now
